<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202141840 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE uninvoiced_purchase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, description TEXT DEFAULT NULL, expense_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payment_method_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_112ED28F5AA1164F ON uninvoiced_purchase (payment_method_id)');
        $this->addSql('CREATE INDEX IDX_112ED28F217BBB47 ON uninvoiced_purchase (person_id)');
        $this->addSql('ALTER TABLE uninvoiced_purchase ADD CONSTRAINT FK_112ED28F5AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE uninvoiced_purchase ADD CONSTRAINT FK_112ED28F217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE invoice ADD uninvoiced_purchase_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744E3F033CE FOREIGN KEY (uninvoiced_purchase_id) REFERENCES uninvoiced_purchase (id)');
        $this->addSql('CREATE INDEX IDX_90651744E3F033CE ON invoice (uninvoiced_purchase_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE uninvoiced_purchase DROP CONSTRAINT FK_112ED28F5AA1164F');
        $this->addSql('ALTER TABLE uninvoiced_purchase DROP CONSTRAINT FK_112ED28F217BBB47');
        $this->addSql('DROP TABLE uninvoiced_purchase');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_90651744E3F033CE');
        $this->addSql('DROP INDEX IDX_90651744E3F033CE');
        $this->addSql('ALTER TABLE invoice DROP uninvoiced_purchase_id');
    }
}
