<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119222004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE auth_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_account_id INT NOT NULL, type VARCHAR(50) NOT NULL, identifier VARCHAR(255) NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_auth_user ON auth_method (user_account_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_type_identifier ON auth_method (type, identifier)');
        $this->addSql('CREATE TABLE password_credential (user_account_id INT NOT NULL, password_hash VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (user_account_id))');
        $this->addSql('CREATE TABLE user_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, person_id INT DEFAULT NULL, roles JSON NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE auth_method');
        $this->addSql('DROP TABLE password_credential');
        $this->addSql('DROP TABLE user_account');
    }
}
